import type { AISource } from '@/lib/types'

interface AIBadgeProps {
  source: AISource
  className?: string
}

export default function AIBadge({ source, className = '' }: AIBadgeProps) {
  const isAI = source === 'ai'
  return (
    <span
      className={`inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-full font-medium border ${className}`}
      style={isAI ? {
        background: 'rgba(99,102,241,0.08)',
        color: '#4338ca',
        borderColor: 'rgba(99,102,241,0.25)',
      } : {
        background: 'rgba(0,0,0,0.04)',
        color: '#6b7280',
        borderColor: 'rgba(0,0,0,0.1)',
      }}
      title={isAI ? 'Generated by AI' : 'Rule-based fallback (AI unavailable)'}
    >
      {isAI ? '✦ AI' : '⚙ Fallback'}
    </span>
  )
}
